name: Code Server Base Build 

on:
  push:
    branches: 
      - 'main'
    paths:
      - 'code-server/code-server-base/**'

defaults:
  run:
    shell: bash -leo pipefail {0}

concurrency:
  group: code-server 
  cancel-in-progress: false 

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: build 
        run: |
         echo testing 